Fix NameError when an inter class alias of basic operator is defined
Reproduce-able code is here:

  class Time
     alias + __id__
  end
  require 'power_assert' #=> undefined method `+' for class `BasicObject' (NameError)

Module#owner returns an original class of alias in Ruby 2.0-2.2.
It will be fixed in 2.3. https://bugs.ruby-lang.org/issues/11173